name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    name: unit test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: create dotenv
        run: |
         touch ./.env.test
         echo "PROTOCOL=${{ secrets.PROTOCOL }}" >> ./.env.test
         echo "HOST=${{ secrets.HOST }}" >> ./.env.test
         echo "PORT=${{ secrets.PORT }}" >> ./.env.test
         echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> ./.env.test
         echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> ./.env.test
         echo "TOKEN_USER_SECRET=${{ secrets.TOKEN_USER_SECRET }}" >> ./.env.test
         echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> ./.env.test
         echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> ./.env.test
         echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> ./.env.test
         echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> ./.env.test
         echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> ./.env.test
         echo "GOOGLE_GMAIL=${{ secrets.GOOGLE_GMAIL }}" >> ./.env.test
         echo "GOOGLE_GMAIL_SECRET=${{ secrets.GOOGLE_GMAIL_SECRET }}" >> ./.env.test
         echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./.env.test

      - name: run all unit tests
        run: yarn run test:unit
